---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/ticket_data":
    post:
      summary: input ticket_datum
      parameters: []
      responses:
        '201':
          description: Ticket and Excavator created
        '400':
          description: Invalid Excavator data
      requestBody:
        content:
          application/json:
            schema:
              RequestNumber:
                type: string
              SequenceNumber:
                type: string
              RequestType:
                type: string
              RequestAction:
                type: string
              DateTimes:
                ResponseDueDateTime:
                  type: date_time
              ServiceArea:
                PrimaryServiceAreaCode:
                  SACode:
                    type: string
                AdditionalServiceAreaCodes:
                  SACode:
                    type: array
              Excavator:
                CompanyName:
                  type: string
                Address:
                  type: string
                City:
                  type: string
                State:
                  type: string
                Zip:
                  type: string
                CrewOnsite:
                  type: boolean
              ExcavationInfo:
                DigsiteInfo:
                  WellKnownText:
                    type: string
            examples:
              '0':
                summary: input ticket_datum
                value:
                  RequestNumber: '09252012-00001'
                  SequenceNumber: '2421'
                  RequestType: Normal
                  RequestAction: Restake
                  DateTimes:
                    ResponseDueDateTime: 2011/07/13 23:59:59
                  ServiceArea:
                    PrimaryServiceAreaCode:
                      SACode: ZZGL103
                    AdditionalServiceAreaCodes:
                      SACode:
                      - ZZL01
                      - ZZL02
                      - ZZL03
                  Excavator:
                    CompanyName: John Doe CONSTRUCTION
                    Address: 555 Some RD
                    City: SOME PARK
                    State: ZZ
                    Zip: '55555'
                    CrewOnsite: 'true'
                  ExcavationInfo:
                    DigsiteInfo:
                      WellKnownText: POLYGON((32.07206917625161 -81.13390268058475,32.04064386441295
                        -81.14660562247929,32.02259853170128 -81.08858407706913,32.02434500961698
                        -81.05322183341679,32.042681017283066 -81.05047525138554,32.06537765335268
                        -81.0319358226746,32.078469305179404 -81.01202310294804,32.07963291684719
                        -81.02850259513554,32.07090546831167 -81.07759774894413,32.08806865844325
                        -81.12154306144413,32.07206917625161 -81.13390268058475))
components:
  schemas:
    body:
      RequestNumber:
        type: string
      SequenceNumber:
        type: string
      RequestType:
        type: string
      RequestAction:
        type: string
      DateTimes:
        ResponseDueDateTime:
          type: date_time
      ServiceArea:
        PrimaryServiceAreaCode:
          SACode:
            type: string
        AdditionalServiceAreaCodes:
          SACode:
            type: array
      Excavator:
        CompanyName:
          type: string
        Address:
          type: string
        City:
          type: string
        State:
          type: string
        Zip:
          type: string
        CrewOnsite:
          type: boolean
      ExcavationInfo:
        DigsiteInfo:
          WellKnownText:
            type: string
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1
